baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "website ikna"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "ikna aprilia indriani"
  namecolor: ffc107
  profession: "student"
  github: "https://github.com"
  linkedin: "https://linkedin.com"
  twitter: "https://twitter.com/"
  instagram: "/https://instagram.com/iknaaprl"
  facebook: "https://facebook.com"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Ikna"
  descripe_l2_person: "This is my biodata [here](#projects)"
  skills:
    - name: make up
      percentage: 75
    - name: masak
      percentage: 40
    - name: berenang
      percentage: 60
    - name: rebahan
      percentage: 85

  # Experience
  disable_experience: false
  experience:
    - company: "Google"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "SD"
      branch: "Lempeni"
      university: "SDN 02 Lempeni"
      startedyear: "2010"
      graduation: "2016"
    - degree: "SMP"
      branch: "Tempeh"
      university: "SMP Negeri 01 Tempeh"
      startedyear: "2016"
      graduation: "2019"
    - degree: "SMK"
      branch: "Pasirian"
      university: "SMK Negeri Pasirian"
      startedyear: "2019"
      graduation: "_"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "iknaaprilia@gmail.com"
  number_phone: 085853889127

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
